#Debug日志位置 需要自行创建文件夹
DIR_LOG: .\log\debug.log

#xlsx文件中标识导出路径的sheet名
DIR_SHEET: $输出路径

#源数据文件夹位置,执行程序时导出目录下所有设置的文件数据
SOURCE_DIR: .\exceldata

#转换的文件后缀
CONVENT_EXT: .xlsx

#输出的文件后缀
OUTPUT_EXT: .txt

#定位标识名
POSITION_NAME: string$name
